"""M5 — Web provenance: find the oldest trace, analyze it, optionally retry.

When the pipeline returns inconclusive on a stripped/recompressed image, M5
asks the internet: "has this image been seen before, and does an earlier copy
still carry provenance?" If yes, the verdict is inherited from the upstream
copy through a documented chain.

Three layers of signal from one API call (cheapest first):
  1. Page-context keywords — Google's bestGuessLabels + page titles + URL
     slugs scanned for AI-related terms ("deepfake", "ai generated", etc.)
  2. Domain classification — known AI galleries vs. stock photo sites
  3. Upstream re-analysis — fetch the matched image, run the full pipeline,
     inherit a stronger verdict if the upstream copy has intact provenance

Uses Google Cloud Vision's WEB_DETECTION (1,000 free requests/month) by
default. The search backend is a single function — swap it for TinEye,
SerpApi, or Bing by replacing `_reverse_search`.

Requires: GOOGLE_APPLICATION_CREDENTIALS env var pointing at a service
account JSON, or GOOGLE_CLOUD_API_KEY for key-based auth. When neither is
set, the module reports "no API key configured" and returns gracefully.
"""
from __future__ import annotations

import os
import tempfile
from dataclasses import dataclass
from pathlib import Path
from urllib.parse import urlparse

import requests
from PIL import Image


# ─────────────────────────────────────────────── known AI platforms ──

AI_GALLERY_DOMAINS = {
    "midjourney.com", "civitai.com", "lexica.art", "playground.com",
    "openart.ai", "tensor.art", "leonardo.ai", "dreamstudio.ai",
    "firefly.adobe.com", "labs.openai.com", "deepai.org",
    "stablediffusionweb.com", "nightcafe.studio",
}

STOCK_PHOTO_DOMAINS = {
    "flickr.com", "unsplash.com", "pexels.com", "shutterstock.com",
    "gettyimages.com", "istockphoto.com", "500px.com", "adobe.stock.com",
}


@dataclass
class WebMatch:
    url: str
    page_url: str | None = None
    page_title: str | None = None
    domain: str | None = None
    score: float = 0.0


@dataclass
class SearchResult:
    """Everything the reverse search returns in one object."""
    matches: list[WebMatch]
    best_guess_labels: list[str]   # Google's own description


# Keywords in page titles, URLs, or bestGuessLabels that suggest AI origin.
# Checked against lowercased text; keep entries lowercase.
AI_CONTEXT_KEYWORDS = {
    "ai-generated", "ai generated", "deepfake", "deep fake",
    "ai image", "ai art", "ai created", "ai-created",
    "generated by ai", "made with ai", "artificial intelligence",
    "midjourney", "dall-e", "dall·e", "dalle", "stable diffusion",
    "synthetically generated", "synthetic image", "fake image",
    "ai photo", "ai picture", "generative ai",
}


def _check_page_context(
    search: SearchResult,
) -> tuple[bool, list[str]]:
    """Check if page titles, URLs, or Google's labels suggest AI origin.

    Scans text the API already returned — no extra requests, no page
    fetching, no HTML parsing. Three independent sources of context:
      1. bestGuessLabels — Google's own classification of the image
      2. pageTitle — what editors titled the page the image appears on
      3. URL slugs — often contain descriptive keywords
    """
    signals = []
    # Google's best guess (strongest — Google's own opinion)
    for label in search.best_guess_labels:
        label_lower = label.lower()
        for kw in AI_CONTEXT_KEYWORDS:
            if kw in label_lower:
                signals.append(f"google label: '{label}'")
                break

    # Page titles and URL slugs
    seen_domains: set[str] = set()
    for match in search.matches:
        if match.domain in seen_domains:
            continue  # one signal per domain
        text = ""
        if match.page_title:
            text += " " + match.page_title.lower()
        if match.url:
            slug = match.url.lower().replace("-", " ").replace("_", " ")
            text += " " + slug
        for kw in AI_CONTEXT_KEYWORDS:
            if kw in text:
                if match.page_title and kw in match.page_title.lower():
                    source = f"title: '{match.page_title}'"
                else:
                    source = f"URL at {match.domain}"
                signals.append(source)
                seen_domains.add(match.domain)
                break

    return bool(signals), signals


# ─────────────────────────────── search backend: Google Cloud Vision ──

def _reverse_search(
    image_path: Path, max_results: int = 10,
) -> SearchResult:
    """Reverse image search via Google Cloud Vision WEB_DETECTION.

    Returns matches + bestGuessLabels. Swap this function to change the
    search backend — the rest of M5 doesn't care how matches are found.
    """
    api_key = os.environ.get("GOOGLE_CLOUD_API_KEY")
    if api_key:
        return _search_with_api_key(image_path, api_key, max_results)

    # Try the google-cloud-vision library (service account auth)
    try:
        from google.cloud import vision  # noqa: F401
        return _search_with_client(image_path, max_results)
    except ImportError:
        return SearchResult(matches=[], best_guess_labels=[])
    except Exception:
        return SearchResult(matches=[], best_guess_labels=[])


def _search_with_api_key(
    image_path: Path, api_key: str, max_results: int,
) -> SearchResult:
    """REST API call with an API key (no SDK needed)."""
    import base64

    img_bytes = Path(image_path).read_bytes()
    body = {
        "requests": [{
            "image": {
                "content": base64.b64encode(img_bytes).decode(),
            },
            "features": [{
                "type": "WEB_DETECTION",
                "maxResults": max_results,
            }],
        }]
    }
    resp = requests.post(
        "https://vision.googleapis.com/v1/images:annotate"
        f"?key={api_key}",
        json=body,
        timeout=30,
    )
    resp.raise_for_status()
    web = resp.json()["responses"][0].get("webDetection", {})
    return _parse_vision_response(web)


def _search_with_client(
    image_path: Path, max_results: int,
) -> SearchResult:
    """google-cloud-vision SDK (service account credentials)."""
    from google.cloud import vision

    client = vision.ImageAnnotatorClient()
    content = Path(image_path).read_bytes()
    image = vision.Image(content=content)
    response = client.web_detection(image=image)
    web = response.web_detection
    labels = [
        entry.label
        for entry in (web.best_guess_labels or [])
    ]
    matches = []
    for match in (web.full_matching_images or [])[:max_results]:
        domain = urlparse(match.url).netloc.lstrip("www.")
        matches.append(WebMatch(url=match.url, domain=domain))
    for page in (web.pages_with_matching_images or [])[:max_results]:
        domain = urlparse(page.url).netloc.lstrip("www.")
        title = None
        if hasattr(page, "page_title"):
            title = page.page_title
        matches.append(WebMatch(
            url=page.url,
            page_url=page.url,
            domain=domain,
            page_title=title,
            score=page.score if hasattr(page, "score") else 0.0,
        ))
    return SearchResult(matches=matches, best_guess_labels=labels)


def _parse_vision_response(web: dict) -> SearchResult:
    """Parse the REST API JSON response into a SearchResult.

    Extracts three layers of text from the response:
      - bestGuessLabels: Google's own description of the image
      - pageTitle: the <title> of each page containing the image
      - URL: the page URL (slugs often contain descriptive keywords)
    All used by _check_page_context — zero additional API calls.
    """
    labels = [
        entry.get("label", "")
        for entry in web.get("bestGuessLabels", [])
    ]
    matches = []
    for item in web.get("fullMatchingImages", []):
        domain = urlparse(item["url"]).netloc.lstrip("www.")
        matches.append(WebMatch(url=item["url"], domain=domain))
    for page in web.get("pagesWithMatchingImages", []):
        domain = urlparse(page["url"]).netloc.lstrip("www.")
        matches.append(WebMatch(
            url=page["url"],
            page_url=page["url"],
            domain=domain,
            page_title=page.get("pageTitle"),
            score=page.get("score", 0.0),
        ))
    return SearchResult(matches=matches, best_guess_labels=labels)


# ──────────────────────────────────────────── fetch a remote image ──

def _fetch_image(url: str, timeout: int = 15) -> Path | None:
    """Download an image URL to a temp file. Returns path or None."""
    try:
        resp = requests.get(
            url, timeout=timeout, stream=True,
            headers={"User-Agent": "ai-image-id/0.1"},
        )
        resp.raise_for_status()
        content_type = resp.headers.get("content-type", "")
        if "image" not in content_type and "octet" not in content_type:
            return None
        suffix = ".jpg"
        if "png" in content_type:
            suffix = ".png"
        elif "webp" in content_type:
            suffix = ".webp"
        tmp = tempfile.NamedTemporaryFile(suffix=suffix, delete=False)
        for chunk in resp.iter_content(8192):
            tmp.write(chunk)
        tmp.close()
        Image.open(tmp.name).verify()
        return Path(tmp.name)
    except Exception:
        return None


# ──────────────────────────────────── domain classification helpers ──

def _classify_domain(domain: str | None) -> str:
    """Classify a domain as 'ai_gallery', 'stock_photo', or 'other'."""
    if not domain:
        return "other"
    d = domain.lower().lstrip("www.")
    if any(ai in d for ai in AI_GALLERY_DOMAINS):
        return "ai_gallery"
    if any(stock in d for stock in STOCK_PHOTO_DOMAINS):
        return "stock_photo"
    return "other"


# ─────────────────────────────────────────────── the one function ──

def trace_provenance(
    image_path: str | Path,
    analyze_fn=None,
    detector_ckpt: str | Path | None = None,
    max_depth: int = 2,
    _depth: int = 0,
) -> dict:
    """Find the oldest web trace of an image and analyze it.

    The core loop:
      1. Reverse-search the image
      2. Check page context (titles, labels, URLs for AI keywords)
      3. Classify the matching domains (AI gallery? stock photo?)
      4. Fetch the best candidate match
      5. Run the full pipeline on the fetched copy
      6. If still inconclusive and depth < max_depth, recurse

    Returns a dict with the search results, context analysis, the
    upstream analysis (if any), and notes documenting the chain.
    Goes straight into the evidence card's notes.

    Parameters
    ----------
    image_path : path to the local image to search for
    analyze_fn : the pipeline's analyze_image function (passed in to
        avoid circular imports; defaults to analyze_image)
    detector_ckpt : forwarded to analyze_fn
    max_depth : retry hops (default 2)
    """
    image_path = Path(image_path)

    if analyze_fn is None:
        from .main import analyze_image
        analyze_fn = analyze_image

    result = {
        "searched": False,
        "matches_found": 0,
        "best_guess_labels": [],
        "domains": [],
        "ai_gallery_match": False,
        "ai_context_match": False,
        "stock_photo_match": False,
        "upstream_url": None,
        "upstream_verdict": None,
        "chain": [],
        "notes": [],
    }

    # Check API availability
    has_api_key = bool(os.environ.get("GOOGLE_CLOUD_API_KEY"))
    has_credentials = bool(
        os.environ.get("GOOGLE_APPLICATION_CREDENTIALS")
    )
    has_vision_lib = False
    try:
        import google.cloud.vision  # noqa: F401
        has_vision_lib = True
    except ImportError:
        pass

    if not has_api_key and not (has_credentials and has_vision_lib):
        result["notes"].append(
            "M5 unavailable: set GOOGLE_CLOUD_API_KEY or "
            "GOOGLE_APPLICATION_CREDENTIALS + pip install "
            "google-cloud-vision"
        )
        return result

    # 1. Reverse search
    search = _reverse_search(image_path)
    matches = search.matches
    result["searched"] = True
    result["matches_found"] = len(matches)
    result["best_guess_labels"] = search.best_guess_labels

    if not matches:
        result["notes"].append("reverse search returned no matches")
        return result

    # 2a. Classify domains
    domains = list({m.domain for m in matches if m.domain})
    result["domains"] = domains
    domain_types = [_classify_domain(d) for d in domains]
    result["ai_gallery_match"] = "ai_gallery" in domain_types
    result["stock_photo_match"] = "stock_photo" in domain_types

    if result["ai_gallery_match"]:
        ai_doms = [
            d for d, t in zip(domains, domain_types)
            if t == "ai_gallery"
        ]
        result["notes"].append(
            "matches include AI gallery domains: "
            + ", ".join(ai_doms)
        )
    if result["stock_photo_match"]:
        stock_doms = [
            d for d, t in zip(domains, domain_types)
            if t == "stock_photo"
        ]
        result["notes"].append(
            "matches on stock photo platforms: "
            + ", ".join(stock_doms)
        )

    # 2b. Page-context analysis — titles, URLs, Google labels
    context_hit, context_signals = _check_page_context(search)
    result["ai_context_match"] = context_hit
    if context_hit:
        result["notes"].append(
            "web context suggests AI origin "
            f"({len(context_signals)} signals): "
            + "; ".join(context_signals[:5])
        )

    # 3. Fetch and re-analyze the best match
    if _depth >= max_depth:
        result["notes"].append(
            f"max search depth ({max_depth}) reached"
        )
        return result

    for match in matches:
        fetched = _fetch_image(match.url)
        if fetched is None:
            continue

        try:
            kwargs = {}
            if detector_ckpt:
                kwargs["detector_ckpt"] = str(detector_ckpt)
            upstream = analyze_fn(str(fetched), **kwargs)
            result["upstream_url"] = match.url
            result["upstream_verdict"] = upstream.ai_verdict.value
            result["chain"].append({
                "url": match.url,
                "domain": match.domain,
                "verdict": upstream.ai_verdict.value,
                "confidence": upstream.confidence,
            })

            # Upstream has stronger evidence — done
            if upstream.ai_verdict.value in ("verified", "likely"):
                result["notes"].append(
                    f"upstream copy at {match.domain} → "
                    f"{upstream.ai_verdict.value} "
                    f"({upstream.confidence})"
                )
                return result

            # Still inconclusive — retry one level deeper
            if (
                upstream.ai_verdict.value == "inconclusive"
                and _depth + 1 < max_depth
            ):
                deeper = trace_provenance(
                    str(fetched), analyze_fn, detector_ckpt,
                    max_depth, _depth + 1,
                )
                if deeper.get("upstream_verdict") in (
                    "verified", "likely",
                ):
                    result["upstream_url"] = deeper["upstream_url"]
                    result["upstream_verdict"] = (
                        deeper["upstream_verdict"]
                    )
                    result["chain"].extend(deeper["chain"])
                    result["notes"].extend(deeper["notes"])
                    return result

        except Exception as exc:
            result["notes"].append(
                f"failed to analyze {match.domain}: "
                f"{type(exc).__name__}"
            )
        finally:
            try:
                Path(fetched).unlink()
            except Exception:
                pass

    if not result["upstream_verdict"]:
        result["notes"].append(
            f"found {len(matches)} web matches but none "
            f"yielded stronger evidence than the local copy"
        )

    return result
